In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"C:\Users\Ursula Paul\Downloads\italy_total.csv")

In [3]:
data.head()

,date,hospitalized_with_symptoms,intensive_care,total_hospitalized,home_confinement,cumulative_positive_cases,daily_positive_cases,recovered,death,positive_clinical_activity,positive_surveys_tests,cumulative_cases,total_tests,total_people_tested,new_intensive_care,total_positive_molecular_test,total_positive_rapid_antigen_test,molecular_test,rapid_antigen_test
0,2020-02-24,101,26,127,94,221,0,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25,114,35,150,162,311,90,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26,128,36,164,221,385,74,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27,248,56,304,284,588,203,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28,345,64,409,412,821,233,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.columns

Index(['date', 'hospitalized_with_symptoms', 'intensive_care',
       'total_hospitalized', 'home_confinement', 'cumulative_positive_cases',
       'daily_positive_cases', 'recovered', 'death',
       'positive_clinical_activity', 'positive_surveys_tests',
       'cumulative_cases', 'total_tests', 'total_people_tested',
       'new_intensive_care', 'total_positive_molecular_test',
       'total_positive_rapid_antigen_test', 'molecular_test',
       'rapid_antigen_test'],
      dtype='object')

In [5]:
data.tail()

,date,hospitalized_with_symptoms,intensive_care,total_hospitalized,home_confinement,cumulative_positive_cases,daily_positive_cases,recovered,death,positive_clinical_activity,positive_surveys_tests,cumulative_cases,total_tests,total_people_tested,new_intensive_care,total_positive_molecular_test,total_positive_rapid_antigen_test,molecular_test,rapid_antigen_test
1126,2023-03-26,2516,102,2618,135655,138273,-793,25354960,188983,NaN,NaN,25682216,269732554,68219912.0,9.0,9755652.0,15926564.0,101127528.0,168605026.0
1127,2023-03-27,2526,95,2621,133236,135857,-2416,25358589,188999,NaN,NaN,25683445,269760907,68226829.0,6.0,9755827.0,15927618.0,101134031.0,168626876.0
1128,2023-03-28,2548,99,2647,131923,134570,-1287,25364853,189037,NaN,NaN,25688460,269850474,68242476.0,16.0,9757017.0,15931443.0,101151273.0,168699201.0
1129,2023-03-29,2556,96,2652,130662,133314,-1256,25369681,189060,NaN,NaN,25692055,269945304,68259493.0,13.0,9757628.0,15934427.0,101187631.0,168757673.0
1130,2023-03-30,2533,84,2617,131051,133668,354,25372554,189089,NaN,NaN,25695311,270012027,68271423.0,5.0,9758302.0,15937009.0,101201171.0,168810856.0

In [6]:
data.describe()

,hospitalized_with_symptoms,intensive_care,total_hospitalized,home_confinement,cumulative_positive_cases,daily_positive_cases,recovered,death,positive_clinical_activity,positive_surveys_tests,cumulative_cases,total_tests,total_people_tested,new_intensive_care,total_positive_molecular_test,total_positive_rapid_antigen_test,molecular_test,rapid_antigen_test
count,1131.000000,1131.000000,1131.000000,1.131000e+03,1.131000e+03,1131.000000,1.131000e+03,1131.000000,162.000000,162.000000,1.131000e+03,1.131000e+03,1.076000e+03,848.000000,8.050000e+02,8.050000e+02,8.050000e+02,8.050000e+02
mean,9960.704686,966.588859,10927.294430,4.635780e+05,4.745053e+05,117.990274,8.807639e+06,116655.946950,345928.216049,132707.308642,9.398801e+06,1.188458e+08,3.673858e+07,64.533019,6.776828e+06,6.201461e+06,7.526809e+07,8.781989e+07
std,8615.462600,1095.122565,9663.472247,5.114059e+05,5.145508e+05,20599.134875,9.065295e+06,57661.531508,217856.889628,176156.446171,9.269644e+06,9.892583e+07,2.286161e+07,65.206502,2.563483e+06,6.278819e+06,2.293470e+07,6.065759e+07
min,101.000000,26.000000,127.000000,9.400000e+01,2.210000e+02,-116092.000000,1.000000e+00,7.000000,0.000000,0.000000,2.290000e+02,4.324000e+03,9.353100e+05,2.000000,2.351466e+06,9.570000e+02,2.861735e+07,1.168590e+05
25%,3419.000000,226.500000,3644.500000,8.147300e+04,9.285800e+04,-5117.500000,8.350720e+05,57541.500000,223237.500000,25369.750000,1.653220e+06,2.244437e+07,1.557056e+07,22.000000,4.211887e+06,1.580770e+05,5.481216e+07,2.340848e+07
50%,7019.000000,409.000000,7328.000000,3.689970e+05,3.879030e+05,-386.000000,4.344238e+06,129885.000000,236256.500000,50768.500000,4.601749e+06,8.718648e+07,3.470951e+07,37.000000,7.878835e+06,4.615624e+06,8.450722e+07,9.987105e+07
75%,15054.000000,1489.000000,16568.500000,5.948900e+05,6.049200e+05,2556.500000,1.717260e+07,167811.000000,341673.000000,138410.250000,1.792770e+07,2.244835e+08,5.996380e+07,91.250000,9.272232e+06,1.276348e+07,9.637445e+07,1.474789e+08
max,34697.000000,4068.000000,38507.000000,2.713594e+06,2.734906e+06,172462.000000,2.537255e+07,189089.000000,988470.000000,653140.000000,2.569531e+07,2.700120e+08,6.827142e+07,324.000000,9.758302e+06,1.593701e+07,1.012012e+08,1.688109e+08